-- Client entry point. Rojo turns this folder into a LocalScript named "Client";
-- the UI modules are its children.

local ContentSync = require(script:WaitForChild("ContentSync"))
local SpellsClient = require(script:WaitForChild("SpellsClient"))
local HudUI = require(script:WaitForChild("HudUI"))
local SpellTrackerUI = require(script:WaitForChild("SpellTrackerUI"))
local InventoryUI = require(script:WaitForChild("InventoryUI"))
local BorderFadeUI = require(script:WaitForChild("BorderFadeUI"))
local NotificationUI = require(script:WaitForChild("NotificationUI"))
local PartyUI = require(script:WaitForChild("PartyUI"))
local PartyFramesUI = require(script:WaitForChild("PartyFramesUI"))
local PartyMarkerUI = require(script:WaitForChild("PartyMarkerUI"))
local StoreUI = require(script:WaitForChild("StoreUI"))
local ShiftLockController = require(script:WaitForChild("ShiftLockController"))
local TargetingController = require(script:WaitForChild("TargetingController"))
local ChatConfig = require(script:WaitForChild("ChatConfig"))
local GatherFeedbackUI = require(script:WaitForChild("GatherFeedbackUI"))
local DamageIndicatorUI = require(script:WaitForChild("DamageIndicatorUI"))
local LevelUpUI = require(script:WaitForChild("LevelUpUI"))
local EnemyLevelUI = require(script:WaitForChild("EnemyLevelUI"))

ContentSync.start() -- first: overlays backend item defs onto the mirror
SpellsClient.start() -- seeds/auto-places spell hotbar binds (HudUI renders them)
HudUI.start()
SpellTrackerUI.start() -- TFT-style subclass tracker (left edge)
InventoryUI.start()
BorderFadeUI.start()
NotificationUI.start()
PartyUI.start()
PartyFramesUI.start()
PartyMarkerUI.start()
StoreUI.start()
ShiftLockController.start()
TargetingController.start()
ChatConfig.start()
GatherFeedbackUI.start()
DamageIndicatorUI.start()
LevelUpUI.start()
EnemyLevelUI.start()